spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cschat
    username: csuser
    password: cspass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092